<a href="https://colab.research.google.com/github/Skkodnikk/popakota/blob/main/Dvumermass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#1
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
arr2 = np.linspace(1, 10, 6)
arr2.shape = (2, 3)
print(arr2)
arr3 = np.arange(10, 22, 2)
arr3.shape = (2,3)
print(arr3)
arr4 = np.random.randint(1, 10, size=(3, 3))
print(arr4)
arr5 = np.random.rand(3, 3)
print(arr5)


[[1 2 3]
 [4 5 6]]
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
[[10 12 14]
 [16 18 20]]
[[4 3 2]
 [5 9 5]
 [3 4 1]]
[[0.11207452 0.84513526 0.26645601]
 [0.05798248 0.34315229 0.88229515]
 [0.03314242 0.35335372 0.7125442 ]]


In [24]:
#2
import numpy as np
u_arr = np.random.uniform(5, 10, (2, 3))
print(u_arr)
n_arr = np.random.normal(2, 12, (2, 3))
print(n_arr)
e_arr = np.random.exponential(3, (2, 3))
print(e_arr)

[[5.95472351 8.40720283 9.00691042]
 [9.51170202 6.85048988 6.94027669]]
[[19.89446723 16.32231167 -7.39679704]
 [-6.4769963  10.85363993  8.95293961]]
[[0.95912279 1.1203038  8.04952436]
 [1.47368566 5.09185274 5.22890625]]


In [55]:
print(arr4)
print(np.min(arr4, axis=1))

print(np.min(arr4, axis=0))

[[4 3 2]
 [5 9 5]
 [3 4 1]]
[2 5 1]
[3 3 1]


In [27]:
#3
u_mean = np.mean(u_arr)
u_max = np.max(u_arr)
u_min = np.min(u_arr)
u_std = np.std(u_arr)
print("uniform:")
print(u_mean)
print(u_max)
print(u_min)
print(u_std)

n_mean = np.mean(n_arr)
n_max = np.max(n_arr)
n_min = np.min(n_arr)
n_std = np.std(n_arr)
print("normal:")
print(n_mean)
print(n_max)
print(n_min)
print(n_std)

e_mean = np.mean(e_arr)
e_max = np.max(e_arr)
e_min = np.min(e_arr)
e_std = np.std(e_arr)
print("exponential:")
print(e_mean)
print(e_max)
print(e_min)
print(e_std)

uniform:
7.778550892581319
9.51170202277141
5.954723506546712
1.2779039111896808
normal:
7.0249275187487585
19.89446723352335
-7.396797036954975
10.49389314365263
exponential:
3.6538992657707063
8.049524356069359
0.9591227909221361
2.655313376640392


In [47]:
#4
import numpy as np
x1 = 25
sqrt = np.sqrt(x1)
print(sqrt)

x2 = 10
log10 = np.log10(x2)
print(log10)

A1 = np.array([[1, 2], [3, 4]])
B1 = np.array([6, 3])
X1 = np.linalg.solve(A1, B1)
print(X1)

A2 = np.array([[1, 3], [6, 2]])
B2 = np.array([2, 5])
A_inv = np.linalg.inv(A2)
X2 = np.dot(A_inv, B2)
print(X2)

5.0
1.0
[-9.   7.5]
[0.6875 0.4375]


In [72]:
#5
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstack = np.hstack((arr1, arr2))
print("hstack:")
print(hstack)

vstack = np.vstack((arr1, arr2))
print("vstack:")
print(vstack)

column = np.column_stack((arr1, arr2))
print("column:")
print(column)

row = np.row_stack((arr1, arr2))
print("row:")
print(row)

arr = np.arange(12)
split = np.array_split(arr, 3)
print("split:")
for i, sub_arr in enumerate(split):
    print(f"{i + 1}: {sub_arr}")


hstack:
[1 2 3 4 5 6]
vstack:
[[1 2 3]
 [4 5 6]]
column:
[[1 4]
 [2 5]
 [3 6]]
row:
[[1 2 3]
 [4 5 6]]
split:
1: [0 1 2 3]
2: [4 5 6 7]
3: [ 8  9 10 11]


In [66]:
#7
import numpy as np
N = 5
M = 3
matrix = np.random.randint(1, 10, (N, M))
m_sum = 0
m_sum_row = 0
for i in range(N):
    r_sum = np.sum(matrix[i])
    if r_sum > m_sum:
        m_sum = r_sum
        m_sum_row = i
print(matrix)
print(f" {m_sum_row}")
print(f"{m_sum}")

[[6 2 4]
 [6 6 5]
 [9 9 7]
 [6 5 5]
 [3 8 5]]
 2
25
