<a href="https://colab.research.google.com/github/Skkodnikk/popakota/blob/main/%D0%BF%D1%804.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#1
import numpy as i
a1 = i.array([1, 2, 3, 4, 5])
print(a1)
a2 = i.arange(1, 6)
print(a2)
a3 = i.arange(1, 10, 2)
print(a3)
a4 = i.linspace(1, 10, 3)
print(a4)
a5 = i.array([1, 2, 3, 4, 5], dtype=int)
print(a5)

[1 2 3 4 5]
[1 2 3 4 5]
[1 3 5 7 9]
[ 1.   5.5 10. ]
[1 2 3 4 5]


In [8]:
#2
even = i.arange(2, 21, 2)
odd = i.arange(1, 21, 2)
posit = i.linspace(1, 10, 10)
negat = i.linspace(-1, -10, 10)
print("четныe:", even)
print("нечетныe:", odd)
print("положит:", posit)
print("отрицат:", negat)

четныe: [ 2  4  6  8 10 12 14 16 18 20]
нечетныe: [ 1  3  5  7  9 11 13 15 17 19]
положит: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
отрицат: [ -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]


In [9]:
#3
one = i.ones(5)
zero = i.zeros(5)
empty = i.empty(5)
print("из единиц:", one)
print("из нулей:", zero)
print("рандом:", empty)

из единиц: [1. 1. 1. 1. 1.]
из нулей: [0. 0. 0. 0. 0.]
пустой: [4.9e-324 1.5e-323 2.5e-323 3.5e-323 4.4e-323]


In [42]:
#4
import numpy as i
a1 = i.array([1, 2, 3, 4, 5])
a2 = i.arange(1, 6)
a3 = i.arange(1, 10, 2)
a4 = i.linspace(1, 10, 3)
a5 = i.array([1, 2, 3, 4, 5], dtype=int)
sa1 = a1[1:4]
sa2 = a2[3:]
sa3 = a3[:5]
sa4 = a4[2:10]
sa5 = a5[2:]
print(sa1)
print(sa2)
print(sa3)
print(sa4)
print(sa5)

[2 3 4]
[4 5]
[1 3 5 7 9]
[10.]
[3 4 5]


In [17]:
#5
ar = i.array([3, 6, 19, 3, 11, 35])
sum = i.sum(ar)
max = i.max(ar)
min = i.min(ar)
print("Массив:", ar)
print("Сумма:", sum)
print("Макс:", max)
print("Мин:", min)

Массив: [ 3  6 19  3 11 35]
Сумма: 77
Макс: 35
Мин: 3


In [61]:
#6
import numpy as np
A = i.array([3, 4, 13, 8, 17, 16])
A1 = A[::2]
A2 = A[::-2]
M = np.concatenate((A1,A2))
print(A)
print(M)

[ 3  4 13  8 17 16]
[ 3 13 17 16  8  4]


In [21]:
#7
N = 10
A1 = i.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 10])
K = 2
L = 8
sume = i.sum(A1[K-1:L])
print("от", K, "до", L, "=", sume)

от 2 до 8 = 36


In [22]:
#8
C = i.array([1, 3, 5, 7, 9])
B = i.array([2, 4, 6, 8, 10])
summ = C + B
lessm = (C + B) / 4
print("поэлементной сумме:")
print(summ)
print("поэлементно меньше в 4 раза суммы:")
print(lessm)

поэлементной сумме:
[ 3  7 11 15 19]
поэлементно меньше в 4 раза суммы:
[0.75 1.75 2.75 3.75 4.75]


In [27]:
#9
ag = i.array([43, 95, 39, 57, 21, 63])
ars = sorted(ag, key=lambda x: int(str(x)[0]))#
print("по возрастанию первой цифры:")
print(ars)

по возрастанию первой цифры:
[21, 39, 43, 57, 63, 95]


In [28]:
#10
import random
N = 10
ar = [random.randint(1, 100) for _ in range(N)]
max = float('-inf')
maxp = None
for i in range(N-1):
    if ar[i] + ar[i+1] > max:
        max = ar[i] + ar[i+1]
        maxp = (ar[i], ar[i+1])
print("Массив:", ar)
print("Два с максимальной суммой:", maxp)

Массив: [37, 42, 93, 15, 62, 9, 46, 89, 11, 38]
Два с максимальной суммой: (42, 93)


In [57]:
#11
ar = [2, 0, 5, 0, 3, 7, 0, 1, 0, 4]
ar.sort(key=lambda x: x == 0)
print(ar)

[2, 5, 3, 7, 1, 4, 0, 0, 0, 0]


In [ ]:
#12

In [45]:
#13
ab = [3, 6, 2, 9, 7, 1, 5]
maxn = float('-inf')
for i in range(1, len(ab) - 1):
    if ab[i] > ab[i - 1] and ab[i] < ab[i + 1]:
        if ab[i] > maxn:
            maxn = ab[i]
    elif ab[i] < ab[i - 1] and ab[i] > ab[i + 1]:
        if ab[i] > maxn:
            maxn = ab[i]
print(maxn if maxn != float('-inf') else 0)

7
